/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package thefarm;

import thefarm.orchards.apple.model.Apple;
import thefarm.orchards.common.Color;
import thefarm.orchards.common.Core;

public class

App {

    public static void main(String[] args) {
        Apple honeycrisp = new Apple(true, Core.EDIBLE, "tough", "sweet", Color.RED, "large", "crunchy", "bruised");
        System.out.println( honeycrisp );
        System.out.println("and now with changes");
        honeycrisp.setHasStem(false);
        honeycrisp.setCore(Core.PIT);
        System.out.println(honeycrisp.getHasStem());
    }
}
